### ISSUE TITLE
Paramaterize your sql

### ISSUE THREAD

**Issue by mohae** [kyledinh/gongfu#2]
Some of the sql is subject to sql injection: https://github.com/kyledinh/gongfu/blob/4ef5a4acf7ab8782dfac9e7c9ff4df8cdeca2da5/src/go/gongfu/model/chirp.go

**Comment by kyledinh** [comment]
Hi Mohae,

True, this was a simple demo and I didn't want to get too complex. Maybe I should revisit this project and implement an ORM.

**Comment by mohae** [comment]
I understand, it's just that people that are learning often see code like this and assume that it's ok.  Seeing that this was forked and starred a bunch, I thought it would be best to have it done correctly.

I was going to do a pull request with the necessary changes but ran into the import issue and punted instead.

Regards.
