### ISSUE TITLE
incomplete import paths for Go code

### ISSUE THREAD

**Issue by mohae** [kyledinh/gongfu#3]
I was getting the repo to address the sql injection vulnarabilities but ran into problems resulting from the way the import statements were done in the Go files. 

Relative impoorts are not recommended in Go.  In files like `src/go/gongfu/api/spec/spec.go` the `go/gongfu/model` import should be `github.com/kyledinh/gongfu/src/go/gongfu/model`

For more information please refer to https://golang.org/doc/code.html.

**Comment by kyledinh** [comment]
Hi Mohae,

Thanks for you input. I had actually set my gopath in the virtualbox to be '~/gongfu/src' and removed relative paths. (https://github.com/kyledinh/gongfu/commit/6257fba4b488a595b97c7c9f18fe3751808c7a5f)

For the build it looks in this path '~/gongfu/src' then in the global go packages. Let me know if I'm still doing it wrong.

**Comment by mohae** [comment]
Hi kyledinh,

Thanks for the response and update.

The import path isn't relative to your virtualbox or Go $WORKSPACE.  As I mentioned in the initial issue, it would be, an example import path would be:

    import "github.com/kyledinh/gongfu" 

or, for the `cfg` package:

    import "github.com/kyledinh/gongfu/cfg"

This would allow `gongfu` to be go gettable using:

    go get github.com/kyledinh/gongfu

This would make it easier for other people to use your project to learn Go/Angular.

If you don't have a VM with Go installed I have a Packer template for building a Go dev VM:  https://github.com/mohae/packer-templates/tree/master/jessie-lxde-go-vbox

Or for just go, I have a gist:  https://gist.github.com/mohae/1935602b1c027077afed

I had wanted to make the changes necessary to parametize the sql but didn't because of the import path issue.

Regards
